[package]
name = "jobs"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
serde_json.workspace = true
tokio.workspace = true
tou-db.workspace = true
tou-domain.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
