/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as HowToRouteImport } from './routes/how-to'
import { Route as LandPlotsRouteImport } from './routes/land-plots'
import { Route as SpecialOrdersRouteImport } from './routes/special-orders'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAdminRouteRouteImport } from './routes/app/admin/route'
import { Route as AppBoardRouteRouteImport } from './routes/app/board/route'
import { Route as AppCommissionRouteRouteImport } from './routes/app/commission/route'
import { Route as AppFinanceRouteRouteImport } from './routes/app/finance/route'
import { Route as AppNotificationsRouteImport } from './routes/app/notifications'
import { Route as AppOrganizerRouteRouteImport } from './routes/app/organizer/route'
import { Route as AppParticipantRouteRouteImport } from './routes/app/participant/route'
import { Route as AppReportsRouteImport } from './routes/app/reports'
import { Route as AppSecretaryRouteRouteImport } from './routes/app/secretary/route'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthPasswordRouteImport } from './routes/auth/password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as ObjectsIndexRouteImport } from './routes/objects/index'
import { Route as TendersIndexRouteImport } from './routes/tenders/index'
import { Route as TendersTenderIdRouteImport } from './routes/tenders/$tenderId'
import { Route as AppAdminIndexRouteImport } from './routes/app/admin/index'
import { Route as AppAuctionsAuctionIdRouteImport } from './routes/app/auctions/$auctionId'
import { Route as AppBoardIndexRouteImport } from './routes/app/board/index'
import { Route as AppCommissionIndexRouteImport } from './routes/app/commission/index'
import { Route as AppFinanceIndexRouteImport } from './routes/app/finance/index'
import { Route as AppOrganizerIndexRouteImport } from './routes/app/organizer/index'
import { Route as AppOrganizerCalculatorRouteImport } from './routes/app/organizer/calculator'
import { Route as AppOrganizerInvestmentRouteImport } from './routes/app/organizer/investment'
import { Route as AppOrganizerLandRouteImport } from './routes/app/organizer/land'
import { Route as AppOrganizerObjectsRouteImport } from './routes/app/organizer/objects'
import { Route as AppOrganizerSpecialRouteImport } from './routes/app/organizer/special'
import { Route as AppParticipantIndexRouteImport } from './routes/app/participant/index'
import { Route as AppParticipantContractsRouteImport } from './routes/app/participant/contracts'
import { Route as AppSecretaryIndexRouteImport } from './routes/app/secretary/index'
import { Route as AppCommissionTendersTenderIdRouteImport } from './routes/app/commission/tenders.$tenderId'
import { Route as AppOrganizerTendersIndexRouteImport } from './routes/app/organizer/tenders/index'
import { Route as AppOrganizerTendersTenderIdRouteImport } from './routes/app/organizer/tenders/$tenderId'
import { Route as AppOrganizerTendersNewRouteImport } from './routes/app/organizer/tenders/new'
import { Route as AppParticipantApplicationsApplicationIdRouteImport } from './routes/app/participant/applications.$applicationId'
import { Route as AppParticipantApplyTenderIdRouteImport } from './routes/app/participant/apply.$tenderId'
import { Route as AppParticipantSpecialRequestIdRouteImport } from './routes/app/participant/special.$requestId'
import { Route as AppParticipantSpecialNewRouteImport } from './routes/app/participant/special.new'
import { Route as AppSecretaryTendersTenderIdRouteImport } from './routes/app/secretary/tenders.$tenderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToRoute = HowToRouteImport.update({
  id: '/how-to',
  path: '/how-to',
  getParentRoute: () => rootRouteImport,
} as any)
const LandPlotsRoute = LandPlotsRouteImport.update({
  id: '/land-plots',
  path: '/land-plots',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialOrdersRoute = SpecialOrdersRouteImport.update({
  id: '/special-orders',
  path: '/special-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminRouteRoute = AppAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBoardRouteRoute = AppBoardRouteRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCommissionRouteRoute = AppCommissionRouteRouteImport.update({
  id: '/commission',
  path: '/commission',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFinanceRouteRoute = AppFinanceRouteRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrganizerRouteRoute = AppOrganizerRouteRouteImport.update({
  id: '/organizer',
  path: '/organizer',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppParticipantRouteRoute = AppParticipantRouteRouteImport.update({
  id: '/participant',
  path: '/participant',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSecretaryRouteRoute = AppSecretaryRouteRouteImport.update({
  id: '/secretary',
  path: '/secretary',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPasswordRoute = AuthPasswordRouteImport.update({
  id: '/auth/password',
  path: '/auth/password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsIndexRoute = ObjectsIndexRouteImport.update({
  id: '/objects/',
  path: '/objects/',
  getParentRoute: () => rootRouteImport,
} as any)
const TendersIndexRoute = TendersIndexRouteImport.update({
  id: '/tenders/',
  path: '/tenders/',
  getParentRoute: () => rootRouteImport,
} as any)
const TendersTenderIdRoute = TendersTenderIdRouteImport.update({
  id: '/tenders/$tenderId',
  path: '/tenders/$tenderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAuctionsAuctionIdRoute = AppAuctionsAuctionIdRouteImport.update({
  id: '/auctions/$auctionId',
  path: '/auctions/$auctionId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBoardIndexRoute = AppBoardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBoardRouteRoute,
} as any)
const AppCommissionIndexRoute = AppCommissionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCommissionRouteRoute,
} as any)
const AppFinanceIndexRoute = AppFinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFinanceRouteRoute,
} as any)
const AppOrganizerIndexRoute = AppOrganizerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrganizerRouteRoute,
} as any)
const AppOrganizerCalculatorRoute = AppOrganizerCalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => AppOrganizerRouteRoute,
} as any)
const AppOrganizerInvestmentRoute = AppOrganizerInvestmentRouteImport.update({
  id: '/investment',
  path: '/investment',
  getParentRoute: () => AppOrganizerRouteRoute,
} as any)
const AppOrganizerLandRoute = AppOrganizerLandRouteImport.update({
  id: '/land',
  path: '/land',
  getParentRoute: () => AppOrganizerRouteRoute,
} as any)
const AppOrganizerObjectsRoute = AppOrganizerObjectsRouteImport.update({
  id: '/objects',
  path: '/objects',
  getParentRoute: () => AppOrganizerRouteRoute,
} as any)
const AppOrganizerSpecialRoute = AppOrganizerSpecialRouteImport.update({
  id: '/special',
  path: '/special',
  getParentRoute: () => AppOrganizerRouteRoute,
} as any)
const AppParticipantIndexRoute = AppParticipantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppParticipantRouteRoute,
} as any)
const AppParticipantContractsRoute = AppParticipantContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AppParticipantRouteRoute,
} as any)
const AppSecretaryIndexRoute = AppSecretaryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSecretaryRouteRoute,
} as any)
const AppCommissionTendersTenderIdRoute =
  AppCommissionTendersTenderIdRouteImport.update({
    id: '/tenders/$tenderId',
    path: '/tenders/$tenderId',
    getParentRoute: () => AppCommissionRouteRoute,
  } as any)
const AppOrganizerTendersIndexRoute =
  AppOrganizerTendersIndexRouteImport.update({
    id: '/tenders/',
    path: '/tenders/',
    getParentRoute: () => AppOrganizerRouteRoute,
  } as any)
const AppOrganizerTendersTenderIdRoute =
  AppOrganizerTendersTenderIdRouteImport.update({
    id: '/tenders/$tenderId',
    path: '/tenders/$tenderId',
    getParentRoute: () => AppOrganizerRouteRoute,
  } as any)
const AppOrganizerTendersNewRoute = AppOrganizerTendersNewRouteImport.update({
  id: '/tenders/new',
  path: '/tenders/new',
  getParentRoute: () => AppOrganizerRouteRoute,
} as any)
const AppParticipantApplicationsApplicationIdRoute =
  AppParticipantApplicationsApplicationIdRouteImport.update({
    id: '/applications/$applicationId',
    path: '/applications/$applicationId',
    getParentRoute: () => AppParticipantRouteRoute,
  } as any)
const AppParticipantApplyTenderIdRoute =
  AppParticipantApplyTenderIdRouteImport.update({
    id: '/apply/$tenderId',
    path: '/apply/$tenderId',
    getParentRoute: () => AppParticipantRouteRoute,
  } as any)
const AppParticipantSpecialRequestIdRoute =
  AppParticipantSpecialRequestIdRouteImport.update({
    id: '/special/$requestId',
    path: '/special/$requestId',
    getParentRoute: () => AppParticipantRouteRoute,
  } as any)
const AppParticipantSpecialNewRoute =
  AppParticipantSpecialNewRouteImport.update({
    id: '/special/new',
    path: '/special/new',
    getParentRoute: () => AppParticipantRouteRoute,
  } as any)
const AppSecretaryTendersTenderIdRoute =
  AppSecretaryTendersTenderIdRouteImport.update({
    id: '/tenders/$tenderId',
    path: '/tenders/$tenderId',
    getParentRoute: () => AppSecretaryRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/healthz': typeof HealthzRoute
  '/how-to': typeof HowToRoute
  '/land-plots': typeof LandPlotsRoute
  '/special-orders': typeof SpecialOrdersRoute
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/app/board': typeof AppBoardRouteRouteWithChildren
  '/app/commission': typeof AppCommissionRouteRouteWithChildren
  '/app/finance': typeof AppFinanceRouteRouteWithChildren
  '/app/organizer': typeof AppOrganizerRouteRouteWithChildren
  '/app/participant': typeof AppParticipantRouteRouteWithChildren
  '/app/secretary': typeof AppSecretaryRouteRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/reports': typeof AppReportsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/password': typeof AuthPasswordRoute
  '/auth/register': typeof AuthRegisterRoute
  '/tenders/$tenderId': typeof TendersTenderIdRoute
  '/app/': typeof AppIndexRoute
  '/objects/': typeof ObjectsIndexRoute
  '/tenders/': typeof TendersIndexRoute
  '/app/auctions/$auctionId': typeof AppAuctionsAuctionIdRoute
  '/app/organizer/calculator': typeof AppOrganizerCalculatorRoute
  '/app/organizer/investment': typeof AppOrganizerInvestmentRoute
  '/app/organizer/land': typeof AppOrganizerLandRoute
  '/app/organizer/objects': typeof AppOrganizerObjectsRoute
  '/app/organizer/special': typeof AppOrganizerSpecialRoute
  '/app/participant/contracts': typeof AppParticipantContractsRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/board/': typeof AppBoardIndexRoute
  '/app/commission/': typeof AppCommissionIndexRoute
  '/app/finance/': typeof AppFinanceIndexRoute
  '/app/organizer/': typeof AppOrganizerIndexRoute
  '/app/participant/': typeof AppParticipantIndexRoute
  '/app/secretary/': typeof AppSecretaryIndexRoute
  '/app/commission/tenders/$tenderId': typeof AppCommissionTendersTenderIdRoute
  '/app/organizer/tenders/$tenderId': typeof AppOrganizerTendersTenderIdRoute
  '/app/organizer/tenders/new': typeof AppOrganizerTendersNewRoute
  '/app/participant/applications/$applicationId': typeof AppParticipantApplicationsApplicationIdRoute
  '/app/participant/apply/$tenderId': typeof AppParticipantApplyTenderIdRoute
  '/app/participant/special/$requestId': typeof AppParticipantSpecialRequestIdRoute
  '/app/participant/special/new': typeof AppParticipantSpecialNewRoute
  '/app/secretary/tenders/$tenderId': typeof AppSecretaryTendersTenderIdRoute
  '/app/organizer/tenders/': typeof AppOrganizerTendersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/healthz': typeof HealthzRoute
  '/how-to': typeof HowToRoute
  '/land-plots': typeof LandPlotsRoute
  '/special-orders': typeof SpecialOrdersRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/reports': typeof AppReportsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/password': typeof AuthPasswordRoute
  '/auth/register': typeof AuthRegisterRoute
  '/tenders/$tenderId': typeof TendersTenderIdRoute
  '/app': typeof AppIndexRoute
  '/objects': typeof ObjectsIndexRoute
  '/tenders': typeof TendersIndexRoute
  '/app/auctions/$auctionId': typeof AppAuctionsAuctionIdRoute
  '/app/organizer/calculator': typeof AppOrganizerCalculatorRoute
  '/app/organizer/investment': typeof AppOrganizerInvestmentRoute
  '/app/organizer/land': typeof AppOrganizerLandRoute
  '/app/organizer/objects': typeof AppOrganizerObjectsRoute
  '/app/organizer/special': typeof AppOrganizerSpecialRoute
  '/app/participant/contracts': typeof AppParticipantContractsRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/board': typeof AppBoardIndexRoute
  '/app/commission': typeof AppCommissionIndexRoute
  '/app/finance': typeof AppFinanceIndexRoute
  '/app/organizer': typeof AppOrganizerIndexRoute
  '/app/participant': typeof AppParticipantIndexRoute
  '/app/secretary': typeof AppSecretaryIndexRoute
  '/app/commission/tenders/$tenderId': typeof AppCommissionTendersTenderIdRoute
  '/app/organizer/tenders/$tenderId': typeof AppOrganizerTendersTenderIdRoute
  '/app/organizer/tenders/new': typeof AppOrganizerTendersNewRoute
  '/app/participant/applications/$applicationId': typeof AppParticipantApplicationsApplicationIdRoute
  '/app/participant/apply/$tenderId': typeof AppParticipantApplyTenderIdRoute
  '/app/participant/special/$requestId': typeof AppParticipantSpecialRequestIdRoute
  '/app/participant/special/new': typeof AppParticipantSpecialNewRoute
  '/app/secretary/tenders/$tenderId': typeof AppSecretaryTendersTenderIdRoute
  '/app/organizer/tenders': typeof AppOrganizerTendersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/healthz': typeof HealthzRoute
  '/how-to': typeof HowToRoute
  '/land-plots': typeof LandPlotsRoute
  '/special-orders': typeof SpecialOrdersRoute
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/app/board': typeof AppBoardRouteRouteWithChildren
  '/app/commission': typeof AppCommissionRouteRouteWithChildren
  '/app/finance': typeof AppFinanceRouteRouteWithChildren
  '/app/organizer': typeof AppOrganizerRouteRouteWithChildren
  '/app/participant': typeof AppParticipantRouteRouteWithChildren
  '/app/secretary': typeof AppSecretaryRouteRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/reports': typeof AppReportsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/password': typeof AuthPasswordRoute
  '/auth/register': typeof AuthRegisterRoute
  '/tenders/$tenderId': typeof TendersTenderIdRoute
  '/app/': typeof AppIndexRoute
  '/objects/': typeof ObjectsIndexRoute
  '/tenders/': typeof TendersIndexRoute
  '/app/auctions/$auctionId': typeof AppAuctionsAuctionIdRoute
  '/app/organizer/calculator': typeof AppOrganizerCalculatorRoute
  '/app/organizer/investment': typeof AppOrganizerInvestmentRoute
  '/app/organizer/land': typeof AppOrganizerLandRoute
  '/app/organizer/objects': typeof AppOrganizerObjectsRoute
  '/app/organizer/special': typeof AppOrganizerSpecialRoute
  '/app/participant/contracts': typeof AppParticipantContractsRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/board/': typeof AppBoardIndexRoute
  '/app/commission/': typeof AppCommissionIndexRoute
  '/app/finance/': typeof AppFinanceIndexRoute
  '/app/organizer/': typeof AppOrganizerIndexRoute
  '/app/participant/': typeof AppParticipantIndexRoute
  '/app/secretary/': typeof AppSecretaryIndexRoute
  '/app/commission/tenders/$tenderId': typeof AppCommissionTendersTenderIdRoute
  '/app/organizer/tenders/$tenderId': typeof AppOrganizerTendersTenderIdRoute
  '/app/organizer/tenders/new': typeof AppOrganizerTendersNewRoute
  '/app/participant/applications/$applicationId': typeof AppParticipantApplicationsApplicationIdRoute
  '/app/participant/apply/$tenderId': typeof AppParticipantApplyTenderIdRoute
  '/app/participant/special/$requestId': typeof AppParticipantSpecialRequestIdRoute
  '/app/participant/special/new': typeof AppParticipantSpecialNewRoute
  '/app/secretary/tenders/$tenderId': typeof AppSecretaryTendersTenderIdRoute
  '/app/organizer/tenders/': typeof AppOrganizerTendersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/healthz'
    | '/how-to'
    | '/land-plots'
    | '/special-orders'
    | '/app/admin'
    | '/app/board'
    | '/app/commission'
    | '/app/finance'
    | '/app/organizer'
    | '/app/participant'
    | '/app/secretary'
    | '/app/notifications'
    | '/app/reports'
    | '/auth/login'
    | '/auth/password'
    | '/auth/register'
    | '/tenders/$tenderId'
    | '/app/'
    | '/objects/'
    | '/tenders/'
    | '/app/auctions/$auctionId'
    | '/app/organizer/calculator'
    | '/app/organizer/investment'
    | '/app/organizer/land'
    | '/app/organizer/objects'
    | '/app/organizer/special'
    | '/app/participant/contracts'
    | '/app/admin/'
    | '/app/board/'
    | '/app/commission/'
    | '/app/finance/'
    | '/app/organizer/'
    | '/app/participant/'
    | '/app/secretary/'
    | '/app/commission/tenders/$tenderId'
    | '/app/organizer/tenders/$tenderId'
    | '/app/organizer/tenders/new'
    | '/app/participant/applications/$applicationId'
    | '/app/participant/apply/$tenderId'
    | '/app/participant/special/$requestId'
    | '/app/participant/special/new'
    | '/app/secretary/tenders/$tenderId'
    | '/app/organizer/tenders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/healthz'
    | '/how-to'
    | '/land-plots'
    | '/special-orders'
    | '/app/notifications'
    | '/app/reports'
    | '/auth/login'
    | '/auth/password'
    | '/auth/register'
    | '/tenders/$tenderId'
    | '/app'
    | '/objects'
    | '/tenders'
    | '/app/auctions/$auctionId'
    | '/app/organizer/calculator'
    | '/app/organizer/investment'
    | '/app/organizer/land'
    | '/app/organizer/objects'
    | '/app/organizer/special'
    | '/app/participant/contracts'
    | '/app/admin'
    | '/app/board'
    | '/app/commission'
    | '/app/finance'
    | '/app/organizer'
    | '/app/participant'
    | '/app/secretary'
    | '/app/commission/tenders/$tenderId'
    | '/app/organizer/tenders/$tenderId'
    | '/app/organizer/tenders/new'
    | '/app/participant/applications/$applicationId'
    | '/app/participant/apply/$tenderId'
    | '/app/participant/special/$requestId'
    | '/app/participant/special/new'
    | '/app/secretary/tenders/$tenderId'
    | '/app/organizer/tenders'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/healthz'
    | '/how-to'
    | '/land-plots'
    | '/special-orders'
    | '/app/admin'
    | '/app/board'
    | '/app/commission'
    | '/app/finance'
    | '/app/organizer'
    | '/app/participant'
    | '/app/secretary'
    | '/app/notifications'
    | '/app/reports'
    | '/auth/login'
    | '/auth/password'
    | '/auth/register'
    | '/tenders/$tenderId'
    | '/app/'
    | '/objects/'
    | '/tenders/'
    | '/app/auctions/$auctionId'
    | '/app/organizer/calculator'
    | '/app/organizer/investment'
    | '/app/organizer/land'
    | '/app/organizer/objects'
    | '/app/organizer/special'
    | '/app/participant/contracts'
    | '/app/admin/'
    | '/app/board/'
    | '/app/commission/'
    | '/app/finance/'
    | '/app/organizer/'
    | '/app/participant/'
    | '/app/secretary/'
    | '/app/commission/tenders/$tenderId'
    | '/app/organizer/tenders/$tenderId'
    | '/app/organizer/tenders/new'
    | '/app/participant/applications/$applicationId'
    | '/app/participant/apply/$tenderId'
    | '/app/participant/special/$requestId'
    | '/app/participant/special/new'
    | '/app/secretary/tenders/$tenderId'
    | '/app/organizer/tenders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  HealthzRoute: typeof HealthzRoute
  HowToRoute: typeof HowToRoute
  LandPlotsRoute: typeof LandPlotsRoute
  SpecialOrdersRoute: typeof SpecialOrdersRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthPasswordRoute: typeof AuthPasswordRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  TendersTenderIdRoute: typeof TendersTenderIdRoute
  ObjectsIndexRoute: typeof ObjectsIndexRoute
  TendersIndexRoute: typeof TendersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to': {
      id: '/how-to'
      path: '/how-to'
      fullPath: '/how-to'
      preLoaderRoute: typeof HowToRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/land-plots': {
      id: '/land-plots'
      path: '/land-plots'
      fullPath: '/land-plots'
      preLoaderRoute: typeof LandPlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/special-orders': {
      id: '/special-orders'
      path: '/special-orders'
      fullPath: '/special-orders'
      preLoaderRoute: typeof SpecialOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/board': {
      id: '/app/board'
      path: '/board'
      fullPath: '/app/board'
      preLoaderRoute: typeof AppBoardRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/commission': {
      id: '/app/commission'
      path: '/commission'
      fullPath: '/app/commission'
      preLoaderRoute: typeof AppCommissionRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/finance': {
      id: '/app/finance'
      path: '/finance'
      fullPath: '/app/finance'
      preLoaderRoute: typeof AppFinanceRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/organizer': {
      id: '/app/organizer'
      path: '/organizer'
      fullPath: '/app/organizer'
      preLoaderRoute: typeof AppOrganizerRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/participant': {
      id: '/app/participant'
      path: '/participant'
      fullPath: '/app/participant'
      preLoaderRoute: typeof AppParticipantRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/secretary': {
      id: '/app/secretary'
      path: '/secretary'
      fullPath: '/app/secretary'
      preLoaderRoute: typeof AppSecretaryRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/password': {
      id: '/auth/password'
      path: '/auth/password'
      fullPath: '/auth/password'
      preLoaderRoute: typeof AuthPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/': {
      id: '/objects/'
      path: '/objects'
      fullPath: '/objects/'
      preLoaderRoute: typeof ObjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenders/': {
      id: '/tenders/'
      path: '/tenders'
      fullPath: '/tenders/'
      preLoaderRoute: typeof TendersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenders/$tenderId': {
      id: '/tenders/$tenderId'
      path: '/tenders/$tenderId'
      fullPath: '/tenders/$tenderId'
      preLoaderRoute: typeof TendersTenderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/auctions/$auctionId': {
      id: '/app/auctions/$auctionId'
      path: '/auctions/$auctionId'
      fullPath: '/app/auctions/$auctionId'
      preLoaderRoute: typeof AppAuctionsAuctionIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/board/': {
      id: '/app/board/'
      path: '/'
      fullPath: '/app/board/'
      preLoaderRoute: typeof AppBoardIndexRouteImport
      parentRoute: typeof AppBoardRouteRoute
    }
    '/app/commission/': {
      id: '/app/commission/'
      path: '/'
      fullPath: '/app/commission/'
      preLoaderRoute: typeof AppCommissionIndexRouteImport
      parentRoute: typeof AppCommissionRouteRoute
    }
    '/app/finance/': {
      id: '/app/finance/'
      path: '/'
      fullPath: '/app/finance/'
      preLoaderRoute: typeof AppFinanceIndexRouteImport
      parentRoute: typeof AppFinanceRouteRoute
    }
    '/app/organizer/': {
      id: '/app/organizer/'
      path: '/'
      fullPath: '/app/organizer/'
      preLoaderRoute: typeof AppOrganizerIndexRouteImport
      parentRoute: typeof AppOrganizerRouteRoute
    }
    '/app/organizer/calculator': {
      id: '/app/organizer/calculator'
      path: '/calculator'
      fullPath: '/app/organizer/calculator'
      preLoaderRoute: typeof AppOrganizerCalculatorRouteImport
      parentRoute: typeof AppOrganizerRouteRoute
    }
    '/app/organizer/investment': {
      id: '/app/organizer/investment'
      path: '/investment'
      fullPath: '/app/organizer/investment'
      preLoaderRoute: typeof AppOrganizerInvestmentRouteImport
      parentRoute: typeof AppOrganizerRouteRoute
    }
    '/app/organizer/land': {
      id: '/app/organizer/land'
      path: '/land'
      fullPath: '/app/organizer/land'
      preLoaderRoute: typeof AppOrganizerLandRouteImport
      parentRoute: typeof AppOrganizerRouteRoute
    }
    '/app/organizer/objects': {
      id: '/app/organizer/objects'
      path: '/objects'
      fullPath: '/app/organizer/objects'
      preLoaderRoute: typeof AppOrganizerObjectsRouteImport
      parentRoute: typeof AppOrganizerRouteRoute
    }
    '/app/organizer/special': {
      id: '/app/organizer/special'
      path: '/special'
      fullPath: '/app/organizer/special'
      preLoaderRoute: typeof AppOrganizerSpecialRouteImport
      parentRoute: typeof AppOrganizerRouteRoute
    }
    '/app/participant/': {
      id: '/app/participant/'
      path: '/'
      fullPath: '/app/participant/'
      preLoaderRoute: typeof AppParticipantIndexRouteImport
      parentRoute: typeof AppParticipantRouteRoute
    }
    '/app/participant/contracts': {
      id: '/app/participant/contracts'
      path: '/contracts'
      fullPath: '/app/participant/contracts'
      preLoaderRoute: typeof AppParticipantContractsRouteImport
      parentRoute: typeof AppParticipantRouteRoute
    }
    '/app/secretary/': {
      id: '/app/secretary/'
      path: '/'
      fullPath: '/app/secretary/'
      preLoaderRoute: typeof AppSecretaryIndexRouteImport
      parentRoute: typeof AppSecretaryRouteRoute
    }
    '/app/commission/tenders/$tenderId': {
      id: '/app/commission/tenders/$tenderId'
      path: '/tenders/$tenderId'
      fullPath: '/app/commission/tenders/$tenderId'
      preLoaderRoute: typeof AppCommissionTendersTenderIdRouteImport
      parentRoute: typeof AppCommissionRouteRoute
    }
    '/app/organizer/tenders/': {
      id: '/app/organizer/tenders/'
      path: '/tenders'
      fullPath: '/app/organizer/tenders/'
      preLoaderRoute: typeof AppOrganizerTendersIndexRouteImport
      parentRoute: typeof AppOrganizerRouteRoute
    }
    '/app/organizer/tenders/$tenderId': {
      id: '/app/organizer/tenders/$tenderId'
      path: '/tenders/$tenderId'
      fullPath: '/app/organizer/tenders/$tenderId'
      preLoaderRoute: typeof AppOrganizerTendersTenderIdRouteImport
      parentRoute: typeof AppOrganizerRouteRoute
    }
    '/app/organizer/tenders/new': {
      id: '/app/organizer/tenders/new'
      path: '/tenders/new'
      fullPath: '/app/organizer/tenders/new'
      preLoaderRoute: typeof AppOrganizerTendersNewRouteImport
      parentRoute: typeof AppOrganizerRouteRoute
    }
    '/app/participant/applications/$applicationId': {
      id: '/app/participant/applications/$applicationId'
      path: '/applications/$applicationId'
      fullPath: '/app/participant/applications/$applicationId'
      preLoaderRoute: typeof AppParticipantApplicationsApplicationIdRouteImport
      parentRoute: typeof AppParticipantRouteRoute
    }
    '/app/participant/apply/$tenderId': {
      id: '/app/participant/apply/$tenderId'
      path: '/apply/$tenderId'
      fullPath: '/app/participant/apply/$tenderId'
      preLoaderRoute: typeof AppParticipantApplyTenderIdRouteImport
      parentRoute: typeof AppParticipantRouteRoute
    }
    '/app/participant/special/$requestId': {
      id: '/app/participant/special/$requestId'
      path: '/special/$requestId'
      fullPath: '/app/participant/special/$requestId'
      preLoaderRoute: typeof AppParticipantSpecialRequestIdRouteImport
      parentRoute: typeof AppParticipantRouteRoute
    }
    '/app/participant/special/new': {
      id: '/app/participant/special/new'
      path: '/special/new'
      fullPath: '/app/participant/special/new'
      preLoaderRoute: typeof AppParticipantSpecialNewRouteImport
      parentRoute: typeof AppParticipantRouteRoute
    }
    '/app/secretary/tenders/$tenderId': {
      id: '/app/secretary/tenders/$tenderId'
      path: '/tenders/$tenderId'
      fullPath: '/app/secretary/tenders/$tenderId'
      preLoaderRoute: typeof AppSecretaryTendersTenderIdRouteImport
      parentRoute: typeof AppSecretaryRouteRoute
    }
  }
}

interface AppAdminRouteRouteChildren {
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteRouteChildren: AppAdminRouteRouteChildren = {
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteRouteWithChildren = AppAdminRouteRoute._addFileChildren(
  AppAdminRouteRouteChildren,
)

interface AppBoardRouteRouteChildren {
  AppBoardIndexRoute: typeof AppBoardIndexRoute
}

const AppBoardRouteRouteChildren: AppBoardRouteRouteChildren = {
  AppBoardIndexRoute: AppBoardIndexRoute,
}

const AppBoardRouteRouteWithChildren = AppBoardRouteRoute._addFileChildren(
  AppBoardRouteRouteChildren,
)

interface AppCommissionRouteRouteChildren {
  AppCommissionIndexRoute: typeof AppCommissionIndexRoute
  AppCommissionTendersTenderIdRoute: typeof AppCommissionTendersTenderIdRoute
}

const AppCommissionRouteRouteChildren: AppCommissionRouteRouteChildren = {
  AppCommissionIndexRoute: AppCommissionIndexRoute,
  AppCommissionTendersTenderIdRoute: AppCommissionTendersTenderIdRoute,
}

const AppCommissionRouteRouteWithChildren =
  AppCommissionRouteRoute._addFileChildren(AppCommissionRouteRouteChildren)

interface AppFinanceRouteRouteChildren {
  AppFinanceIndexRoute: typeof AppFinanceIndexRoute
}

const AppFinanceRouteRouteChildren: AppFinanceRouteRouteChildren = {
  AppFinanceIndexRoute: AppFinanceIndexRoute,
}

const AppFinanceRouteRouteWithChildren = AppFinanceRouteRoute._addFileChildren(
  AppFinanceRouteRouteChildren,
)

interface AppOrganizerRouteRouteChildren {
  AppOrganizerCalculatorRoute: typeof AppOrganizerCalculatorRoute
  AppOrganizerInvestmentRoute: typeof AppOrganizerInvestmentRoute
  AppOrganizerLandRoute: typeof AppOrganizerLandRoute
  AppOrganizerObjectsRoute: typeof AppOrganizerObjectsRoute
  AppOrganizerSpecialRoute: typeof AppOrganizerSpecialRoute
  AppOrganizerIndexRoute: typeof AppOrganizerIndexRoute
  AppOrganizerTendersTenderIdRoute: typeof AppOrganizerTendersTenderIdRoute
  AppOrganizerTendersNewRoute: typeof AppOrganizerTendersNewRoute
  AppOrganizerTendersIndexRoute: typeof AppOrganizerTendersIndexRoute
}

const AppOrganizerRouteRouteChildren: AppOrganizerRouteRouteChildren = {
  AppOrganizerCalculatorRoute: AppOrganizerCalculatorRoute,
  AppOrganizerInvestmentRoute: AppOrganizerInvestmentRoute,
  AppOrganizerLandRoute: AppOrganizerLandRoute,
  AppOrganizerObjectsRoute: AppOrganizerObjectsRoute,
  AppOrganizerSpecialRoute: AppOrganizerSpecialRoute,
  AppOrganizerIndexRoute: AppOrganizerIndexRoute,
  AppOrganizerTendersTenderIdRoute: AppOrganizerTendersTenderIdRoute,
  AppOrganizerTendersNewRoute: AppOrganizerTendersNewRoute,
  AppOrganizerTendersIndexRoute: AppOrganizerTendersIndexRoute,
}

const AppOrganizerRouteRouteWithChildren =
  AppOrganizerRouteRoute._addFileChildren(AppOrganizerRouteRouteChildren)

interface AppParticipantRouteRouteChildren {
  AppParticipantContractsRoute: typeof AppParticipantContractsRoute
  AppParticipantIndexRoute: typeof AppParticipantIndexRoute
  AppParticipantApplicationsApplicationIdRoute: typeof AppParticipantApplicationsApplicationIdRoute
  AppParticipantApplyTenderIdRoute: typeof AppParticipantApplyTenderIdRoute
  AppParticipantSpecialRequestIdRoute: typeof AppParticipantSpecialRequestIdRoute
  AppParticipantSpecialNewRoute: typeof AppParticipantSpecialNewRoute
}

const AppParticipantRouteRouteChildren: AppParticipantRouteRouteChildren = {
  AppParticipantContractsRoute: AppParticipantContractsRoute,
  AppParticipantIndexRoute: AppParticipantIndexRoute,
  AppParticipantApplicationsApplicationIdRoute:
    AppParticipantApplicationsApplicationIdRoute,
  AppParticipantApplyTenderIdRoute: AppParticipantApplyTenderIdRoute,
  AppParticipantSpecialRequestIdRoute: AppParticipantSpecialRequestIdRoute,
  AppParticipantSpecialNewRoute: AppParticipantSpecialNewRoute,
}

const AppParticipantRouteRouteWithChildren =
  AppParticipantRouteRoute._addFileChildren(AppParticipantRouteRouteChildren)

interface AppSecretaryRouteRouteChildren {
  AppSecretaryIndexRoute: typeof AppSecretaryIndexRoute
  AppSecretaryTendersTenderIdRoute: typeof AppSecretaryTendersTenderIdRoute
}

const AppSecretaryRouteRouteChildren: AppSecretaryRouteRouteChildren = {
  AppSecretaryIndexRoute: AppSecretaryIndexRoute,
  AppSecretaryTendersTenderIdRoute: AppSecretaryTendersTenderIdRoute,
}

const AppSecretaryRouteRouteWithChildren =
  AppSecretaryRouteRoute._addFileChildren(AppSecretaryRouteRouteChildren)

interface AppRouteRouteChildren {
  AppAdminRouteRoute: typeof AppAdminRouteRouteWithChildren
  AppBoardRouteRoute: typeof AppBoardRouteRouteWithChildren
  AppCommissionRouteRoute: typeof AppCommissionRouteRouteWithChildren
  AppFinanceRouteRoute: typeof AppFinanceRouteRouteWithChildren
  AppOrganizerRouteRoute: typeof AppOrganizerRouteRouteWithChildren
  AppParticipantRouteRoute: typeof AppParticipantRouteRouteWithChildren
  AppSecretaryRouteRoute: typeof AppSecretaryRouteRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAuctionsAuctionIdRoute: typeof AppAuctionsAuctionIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRouteRoute: AppAdminRouteRouteWithChildren,
  AppBoardRouteRoute: AppBoardRouteRouteWithChildren,
  AppCommissionRouteRoute: AppCommissionRouteRouteWithChildren,
  AppFinanceRouteRoute: AppFinanceRouteRouteWithChildren,
  AppOrganizerRouteRoute: AppOrganizerRouteRouteWithChildren,
  AppParticipantRouteRoute: AppParticipantRouteRouteWithChildren,
  AppSecretaryRouteRoute: AppSecretaryRouteRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppReportsRoute: AppReportsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAuctionsAuctionIdRoute: AppAuctionsAuctionIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  HealthzRoute: HealthzRoute,
  HowToRoute: HowToRoute,
  LandPlotsRoute: LandPlotsRoute,
  SpecialOrdersRoute: SpecialOrdersRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthPasswordRoute: AuthPasswordRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  TendersTenderIdRoute: TendersTenderIdRoute,
  ObjectsIndexRoute: ObjectsIndexRoute,
  TendersIndexRoute: TendersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
