[package]
name = "tou-testkit"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
thiserror.workspace = true

[dev-dependencies]
sqlx.workspace = true
tokio.workspace = true
tou-db.workspace = true
jiff.workspace = true
rust_decimal.workspace = true
time.workspace = true
tou-domain.workspace = true
uuid.workspace = true
